Dataloader:
  train_batch_size: 8
  val_batch_size: 4
  test_batch_size: 4
Transform:
  train_random_crop_size: [320, 320]
Model:
  encoder: timm-efficientnet-b5
  siamese_head_kernel_size_last: 7
  n_siamese_head_convs: 1